[server]
headless = true
runOnSave = true
enableStaticServing = true

[[theme.fontFaces]]
family="Intro"
url="app/static/Intro.ttf"
style="normal"
weight=400
[[theme.fontFaces]]
family="Questrial"
url="app/static/Questrial-Regular.ttf"
style="normal"
weight=400

[theme]
base="dark"
primaryColor="#8b0a20"
font="Questrial"
headingFont="Intro"
headingFontSizes=["3rem", "2.875rem", "2.75rem"]
chartCategoricalColors = [
    "#83c9ff", # blue40
    "#0068c9", # blue80
    "#ffabab", # red40
    "#ff2b2b", # red80
    "#7defa1", # green40
    "#29b09d", # blueGreen80
    "#ffd16a", # orange50
    "#ff8700", # orange80
    "#6d3fc0", # purple80
    "#d5dae5", # gray40
]
chartSequentialColors  = [
    "#83c9ff", # blue40
    "#0068c9", # blue80
    "#ffabab", # red40
    "#ff2b2b", # red80
    "#7defa1", # green40
    "#29b09d", # blueGreen80
    "#ffd16a", # orange50
    "#ff8700", # orange80
    "#6d3fc0", # purple80
    "#d5dae5", # gray40
]

[runner]
fastReruns = true